import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/services/local_cache_service.dart';
import '../../../core/services/notification_service.dart';
import '../../../core/services/offline_queue_service.dart';
import '../../../core/services/sync_service.dart';
import '../../family/providers/family_provider.dart';
import '../../medicines/data/medicine_repository.dart';
import '../../medicines/providers/medicine_provider.dart';
import '../data/reminder_model.dart';
import '../data/reminder_repository.dart';

final reminderRepositoryProvider = Provider<ReminderRepository>((ref) {
  return ReminderRepository();
});

/// Reminder times for a single medicine — used on the "Manage Reminders"
/// screen reached from Medicine Detail.
final medicineScheduleProvider = FutureProvider.family<List<MedicineSchedule>,
    String>((ref, medicineId) {
  return ref.watch(reminderRepositoryProvider).fetchScheduleForMedicine(medicineId);
});

class ScheduleController extends StateNotifier<AsyncValue<void>> {
  ScheduleController(this._repository, this._medicineId, this._medicineName)
      : super(const AsyncValue.data(null));

  final ReminderRepository _repository;
  final String _medicineId;
  final String _medicineName;

  Future<void> addTime(MedicineSchedule schedule) async {
    state = const AsyncValue.loading();
    try {
      final created = await _repository.addScheduleTime(schedule, _medicineId);
      final today = DateTime.now();
      final scheduledToday = DateTime(
        today.year,
        today.month,
        today.day,
        created.timeOfDay.hour,
        created.timeOfDay.minute,
      );
      await NotificationService.instance.scheduleDoseReminder(
        notificationId: NotificationService.idFromScheduleId(created.id),
        medicineName: _medicineName,
        dosageLabel: created.label,
        scheduledTime: scheduledToday,
        payload: created.id,
      );
      state = const AsyncValue.data(null);
    } catch (e, st) {
      state = AsyncValue.error(e, st);
    }
  }

  Future<void> removeTime(String scheduleId) async {
    state = const AsyncValue.loading();
    try {
      await _repository.removeScheduleTime(scheduleId);
      await NotificationService.instance
          .cancelReminder(NotificationService.idFromScheduleId(scheduleId));
      state = const AsyncValue.data(null);
    } catch (e, st) {
      state = AsyncValue.error(e, st);
    }
  }
}

final scheduleControllerProvider = StateNotifierProvider.family<
    ScheduleController, AsyncValue<void>, ({String medicineId, String medicineName})>(
  (ref, args) => ScheduleController(
    ref.watch(reminderRepositoryProvider),
    args.medicineId,
    args.medicineName,
  ),
);

/// Today's doses for whichever profile is currently selected (Module 11)
/// — this is what makes the Dashboard's progress ring and "Today's
/// Medicines" list real, and now per-person rather than account-wide.
class TodayDosesController extends StateNotifier<AsyncValue<List<DoseLog>>> {
  TodayDosesController(this._repository, this._medicineRepository, this._profileId)
      : super(const AsyncValue.loading()) {
    load();
  }

  final ReminderRepository _repository;
  final MedicineRepository _medicineRepository;
  final String? _profileId;
  final _cache = LocalCacheService.instance;

  String get _cacheKey => 'today_doses_${_profileId ?? 'none'}';

  Future<void> load() async {
    final profileId = _profileId;
    if (profileId == null) {
      state = const AsyncValue.data([]);
      return;
    }
    state = const AsyncValue.loading();
    // Module 15: attempt to push any offline-queued confirmations before
    // pulling fresh data, so a reconnect doesn't show stale "upcoming"
    // status for a dose the user already confirmed while offline.
    await SyncService.instance.syncPendingActions();
    try {
      // Module 5: make sure today's schedule has actually turned into
      // dose rows, and anything overdue past the grace window is
      // reflected as missed, before we show the list.
      await _repository.generateTodayDoseEntries(profileId);
      // Module 12: check every profile on this account for missed doses,
      // not just the one currently selected — a caregiver viewing
      // "Myself" still needs to know if "Mother" just missed a dose.
      await _repository.checkMissedDosesAcrossAllProfiles();
      final doses = await _repository.fetchTodayDoses(profileId);
      state = AsyncValue.data(doses);
      await _cache.save(_cacheKey, doses.map((d) => d.toCacheJson()).toList());
    } catch (e, st) {
      // Module 15: offline fallback — show the last-cached snapshot
      // rather than an error screen, since "view today's doses" is one
      // of the PRD's explicit offline requirements. Note this can't
      // include doses generated by generateTodayDoseEntries() above,
      // since that write also failed — see the README's honest note on
      // what offline mode does and doesn't cover.
      final cached = await _cache.load(_cacheKey);
      if (cached != null) {
        state = AsyncValue.data(cached.map(DoseLog.fromCacheJson).toList());
      } else {
        state = AsyncValue.error(e, st);
      }
    }
  }

  Future<void> markTaken(String doseId) => _updateStatus(doseId, DoseStatus.taken);
  Future<void> markSkipped(String doseId) =>
      _updateStatus(doseId, DoseStatus.skipped);

  Future<void> _updateStatus(String doseId, DoseStatus status) async {
    final previous = state;
    state = state.whenData((doses) => [
          for (final d in doses)
            if (d.id == doseId)
              DoseLog(
                id: d.id,
                medicineId: d.medicineId,
                medicineName: d.medicineName,
                dosageLabel: d.dosageLabel,
                scheduleId: d.scheduleId,
                scheduledTime: d.scheduledTime,
                respondedTime: DateTime.now(),
                status: status,
              )
            else
              d,
        ]);
    try {
      await _repository.markDose(doseId, status);
      if (status == DoseStatus.taken) {
        final dose = previous.value?.firstWhere((d) => d.id == doseId);
        if (dose != null) {
          // Decrements by 1 unit per confirmed dose. Doesn't yet account
          // for medicines where a single dose is >1 unit (e.g. "2 tablets")
          // — that needs a units-per-dose field on MedicineSchedule,
          // a reasonable next refinement rather than a Module 5 blocker.
          await _medicineRepository.decrementStock(dose.medicineId, 1);
        }
      }
    } catch (e) {
      // Module 15: rather than rolling back to "upcoming" and losing the
      // user's action, queue it locally and KEEP the optimistic update —
      // the confirmation the user made is real to them even if it hasn't
      // reached the server yet. SyncService replays this on next load()
      // or on the connectivity-restored listener in main.dart.
      await OfflineQueueService.instance.enqueue(
        QueuedDoseAction(
          doseId: doseId,
          type: status == DoseStatus.taken
              ? QueuedActionType.taken
              : QueuedActionType.skipped,
          queuedAt: DateTime.now(),
        ),
      );
    }
  }
}

final todayDosesProvider =
    StateNotifierProvider<TodayDosesController, AsyncValue<List<DoseLog>>>(
        (ref) {
  final profile = ref.watch(selectedProfileProvider);
  return TodayDosesController(
    ref.watch(reminderRepositoryProvider),
    ref.watch(medicineRepositoryProvider),
    profile?.id,
  );
});

/// Weekly adherence % + streak for the selected profile — feeds the
/// Dashboard's stats row.
final adherenceStatsProvider =
    FutureProvider<({double adherencePercent, int streak})>((ref) {
  ref.watch(todayDosesProvider); // refresh stats when today's doses change
  final profile = ref.watch(selectedProfileProvider);
  if (profile == null) return Future.value((adherencePercent: 0.0, streak: 0));
  return ref.watch(reminderRepositoryProvider).fetchAdherenceStats(profile.id);
});

/// 7-day dominant status per day for the selected profile — feeds the
/// Dashboard's mini calendar strip.
final weekCalendarProvider =
    FutureProvider<List<({DateTime date, DoseStatus status})>>((ref) {
  ref.watch(todayDosesProvider);
  final profile = ref.watch(selectedProfileProvider);
  if (profile == null) return Future.value([]);
  return ref.watch(reminderRepositoryProvider).fetchWeekCalendar(profile.id);
});
